### PR TITLE
Add YAML format output

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/hugovk/norwegianblue/issues/137.

For example:

```yaml
$ eol python --format yaml
- cycle: '3.11'
  eol: '2027-10-24'
  latest: 3.11.2
  latest release: '2023-02-07'
  release: '2022-10-24'
- cycle: '3.10'
  eol: '2026-10-04'
  latest: 3.10.10
  latest release: '2023-02-07'
  release: '2021-10-04'
- cycle: '3.9'
  eol: '2025-10-05'
  latest: 3.9.16
  latest release: '2022-12-06'
  release: '2020-10-05'
- cycle: '3.8'
  eol: '2024-10-14'
  latest: 3.8.16
  latest release: '2022-12-06'
  release: '2019-10-14'
- cycle: '3.7'
  eol: '2023-06-27'
  latest: 3.7.16
  latest release: '2022-12-06'
  release: '2018-06-26'
- cycle: '3.6'
  eol: '2021-12-23'
  latest: 3.6.15
  latest release: '2021-09-03'
  release: '2016-12-22'
- cycle: '3.5'
  eol: '2020-09-13'
  latest: 3.5.10
  latest release: '2020-09-05'
  release: '2015-09-12'
- cycle: '3.4'
  eol: '2019-03-18'
  latest: 3.4.10
  latest release: '2019-03-18'
  release: '2014-03-15'
- cycle: '3.3'
  eol: '2017-09-29'
  latest: 3.3.7
  latest release: '2017-09-19'
  release: '2012-09-29'
- cycle: '2.7'
  eol: '2020-01-01'
  latest: 2.7.18
  latest release: '2020-04-19'
  release: '2010-07-03'
- cycle: '2.6'
  eol: '2013-10-29'
  latest: 2.6.9
  latest release: '2013-10-29'
  release: '2008-10-01'

```

### CODE REVIEW

**Comment by adriens** [comment]
Looks really cool :sunglasses:

**Comment by adriens** [comment]
:thinking: COuld you share an output example while querying for more than a single product :grey_question: :pray:

**Comment by hugovk** [comment]
Sure:

```yaml
$ eol python drupal --format yaml
python:
- cycle: '3.11'
  eol: '2027-10-24'
  latest: 3.11.2
  latest release: '2023-02-07'
  release: '2022-10-24'
- cycle: '3.10'
  eol: '2026-10-04'
  latest: 3.10.10
  latest release: '2023-02-07'
  release: '2021-10-04'
- cycle: '3.9'
  eol: '2025-10-05'
  latest: 3.9.16
  latest release: '2022-12-06'
  release: '2020-10-05'
- cycle: '3.8'
  eol: '2024-10-14'
  latest: 3.8.16
  latest release: '2022-12-06'
  release: '2019-10-14'
- cycle: '3.7'
  eol: '2023-06-27'
  latest: 3.7.16
  latest release: '2022-12-06'
  release: '2018-06-26'
- cycle: '3.6'
  eol: '2021-12-23'
  latest: 3.6.15
  latest release: '2021-09-03'
  release: '2016-12-22'
- cycle: '3.5'
  eol: '2020-09-13'
  latest: 3.5.10
  latest release: '2020-09-05'
  release: '2015-09-12'
- cycle: '3.4'
  eol: '2019-03-18'
  latest: 3.4.10
  latest release: '2019-03-18'
  release: '2014-03-15'
- cycle: '3.3'
  eol: '2017-09-29'
  latest: 3.3.7
  latest release: '2017-09-19'
  release: '2012-09-29'
- cycle: '2.7'
  eol: '2020-01-01'
  latest: 2.7.18
  latest release: '2020-04-19'
  release: '2010-07-03'
- cycle: '2.6'
  eol: '2013-10-29'
  latest: 2.6.9
  latest release: '2013-10-29'
  release: '2008-10-01'


drupal:
- cycle: '10.0'
  eol: '2023-12-13'
  latest: 10.0.3
  latest release: '2023-02-01'
  release: '2022-12-15'
  support: '2023-06-21'
- cycle: '9.5'
  eol: '2023-11-01'
  latest: 9.5.3
  latest release: '2023-02-01'
  release: '2022-12-15'
  support: '2023-06-21'
- cycle: '9.4'
  eol: '2023-06-21'
  latest: 9.4.11
  latest release: '2023-02-01'
  release: '2022-06-15'
  support: '2022-12-14'
- cycle: '9.3'
  eol: '2022-12-14'
  latest: 9.3.22
  latest release: '2022-09-28'
  release: '2021-12-08'
  support: '2022-06-15'
- cycle: '9.2'
  eol: '2022-06-15'
  latest: 9.2.21
  latest release: '2022-06-10'
  release: '2021-06-16'
  support: '2021-12-08'
- cycle: '9.1'
  eol: '2021-12-08'
  latest: 9.1.15
  latest release: '2021-11-24'
  release: '2020-12-02'
  support: '2021-06-16'
- cycle: '9.0'
  eol: '2021-06-16'
  latest: 9.0.14
  latest release: '2021-05-25'
  release: '2020-06-03'
  support: '2020-12-02'
- cycle: '8.9'
  eol: '2021-11-02'
  latest: 8.9.20
  latest release: '2021-11-17'
  release: '2020-06-03'
  support: '2020-12-01'
- cycle: '8.8'
  eol: '2020-12-01'
  latest: 8.8.12
  latest release: '2020-11-25'
  release: '2019-12-04'
  support: '2020-06-03'
- cycle: 7 LTS
  eol: '2023-11-01'
  latest: '7.94'
  latest release: '2022-12-14'
  release: '2011-01-05'
  support: '2015-11-19'


```

Both pass validation at https://www.yamllint.com/

**Comment by adriens** [comment]
It looks really cool :sunglasses:

**Comment by adriens** [comment]
:fireworks: 

BTW... cooleagues at the office `eol` really cool... it becomes everyday a bit more a part of our stack at [`opt-nc`](https://github.com/opt-nc)

**Comment by hugovk** [comment]
Nice to hear! Also huge thanks for all your work and the rest of the team's at https://endoflife.date!

**Comment by adriens** [comment]
😘

**Pull request merged**
