### PR TITLE
Enable colour on Windows

### LINKED ISSUE #8: Use colorama for Windows support
@hugovk small suggestion :
add `colorize` into your install_requires and also make small changes  to your src/norwegianblue/__init__.py  : 
change :
```python
from termcolor import colored
```
to
```python
from colorama import init
from termcolor import colored
init()
```
this will let color also works on windows systems
termcolor is really old module and doesnt support some systems so using colorama and termcolor together
will fix all problems.

_Originally posted by @usta in https://github.com/endoflife-date/endoflife.date/issues/273#issuecomment-882052650_

---

Will make it a conditional install for Windows only.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #8.

Install and init colorama on Windows.

### CODE REVIEW

**Comment by hugovk** [comment]
@usta Please could you try this out on Windows?

**Comment by usta** [comment]
i will try tomorrow morning, but you dont need to specify for just windows , it also enables true color support for linux too.

**Comment by hugovk** [comment]
Is it needed for Linux?

https://github.com/tartley/colorama#initialisation says it's only needed for Windows and is a no-op for other platforms:

> On Windows, calling `init()` will filter ANSI escape sequences out of any text sent to stdout or stderr, and replace them with equivalent Win32 calls.
> 
> On other platforms, calling `init()` has no effect (unless you request other optional functionality; see "Init Keyword Args", below). By design, this permits applications to call `init()` unconditionally on all platforms, after which ANSI output should just work.

I tried the existing release on Debian 10 and it showed colour output:

image

**Comment by hugovk** [comment]
@usta Hi! Did you get a chance to try this yet?

**Comment by hugovk** [comment]
Doesn't seem necessary, can re-open if needed in the future.

**Pull request closed without merging**
